### ISSUE TITLE
bug: Compiler panics on array sum example when explicitly type annotated

### ISSUE THREAD

**Issue by jmcph4** [starkware-libs/cairo#1233]
# Bug Report

**Cairo version:**

```
$ git rev-parse HEAD
03553bd52053dec7fbe49da9cd6c4679843c030a
```

**Current behavior:**

```
$ cd crates/compiler
$ cat array_sum.cairo
// Computes the sum of the memory elements at addresses:
//   arr + 0, arr + 1, ..., arr + (size - 1).
func array_sum(arr: felt*, size: felt) -> felt {
    if (size == 0) {
        return 0;
    }

    // size is not zero.
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
    return arr[0] + sum_of_rest;
}
$ cargo run array_sum.cairo
error: Missing token TerminalComma.
 --> array_sum.cairo:3:25
func array_sum(arr: felt*, size: felt) -> felt {
                        ^

error: Skipped tokens. Expected: parameter.
 --> array_sum.cairo:3:25
func array_sum(arr: felt*, size: felt) -> felt {
                        ^

error: Skipped tokens. Expected: parameter.
 --> array_sum.cairo:3:26
func array_sum(arr: felt*, size: felt) -> felt {
                         ^

error: Missing token TerminalSemicolon.
 --> array_sum.cairo:10:15
    return arr[0] + sum_of_rest;
              ^

error: Skipped tokens. Expected: statement.
 --> array_sum.cairo:10:15
    return arr[0] + sum_of_rest;
              ^

error: Skipped tokens. Expected: statement.
 --> array_sum.cairo:10:17
    return arr[0] + sum_of_rest;
                ^

error: Skipped tokens. Expected: statement.
 --> array_sum.cairo:10:19
    return arr[0] + sum_of_rest;
                  ^

error: Cannot assign to an immutable variable.
 --> array_sum.cairo:9:33
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                ^*********^

error: Cannot assign to an immutable variable.
 --> array_sum.cairo:9:46
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                             ^***********^

error: Unexpected argument type. Expected: "core::felt", found: "()".
 --> array_sum.cairo:9:33
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                ^*********^

error: Unexpected argument type. Expected: "core::felt", found: "()".
 --> array_sum.cairo:9:46
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                             ^***********^

error: Unexpected return type. Expected: "core::felt", found: "()".
 --> array_sum.cairo:3:48
func array_sum(arr: felt*, size: felt) -> felt {
                                               ^

error: Unreachable code
 --> array_sum.cairo:10:16
    return arr[0] + sum_of_rest;
               ^***************^

thread 'main' panicked at 'Internal compiler error: Found a reachable statement at the end of the function.', crates/sierra_generator/src/store_variables/mod.rs:328:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Associated backtrace (with `RUST_BACKTRACE=full`):

```
stack backtrace:
   0:     0x560317402380 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x560317402380 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560317402380 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x560317402380 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x560317422e0e - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x5603173ff895 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x560317403a03 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x560317403a03 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x560317403a03 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x5603174036ef - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x5603174040aa - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:     0x560317403f61 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  12:     0x56031740282c - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x560317403cc2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:     0x5603161980e3 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:     0x56031622abc8 - sierra_generator::store_variables::AddStoreVariableStatements::finalize::h36830de016f3296d
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/store_variables/mod.rs:328:9
  16:     0x56031622887c - sierra_generator::store_variables::add_store_statements::he4ad188b682d1664
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/store_variables/mod.rs:51:5
  17:     0x5603162121ab - sierra_generator::function_generator::get_function_code::h2a73143ec4958829
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/function_generator.rs:117:22
  18:     0x560316210d3f - sierra_generator::function_generator::priv_free_function_sierra_data::hab5f8418368d5818
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/function_generator.rs:46:20
  19:     0x5603161d80c7 - <sierra_generator::db::PrivFreeFunctionSierraDataQuery as salsa::plumbing::QueryFunction>::execute::hc6d66b60052cef2f
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:60:21
  20:     0x56031629fe94 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}::h0b8cba695b7e60d8
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:218:13
  21:     0x5603163a4843 - salsa::runtime::Runtime::execute_query_implementation::h1a50a80a72e907c2
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/runtime.rs:330:21
  22:     0x560316294d84 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::he5d05cf2c1d00fc4
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:215:26
  23:     0x5603162b63be - salsa::derived::slot::Slot<Q,MP>::read::he126cfc7920fc701
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:148:9
  24:     0x56031620cfb6 - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::ha5feccfb396f28a8
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived.rs:170:13
  25:     0x56031631d6c0 - salsa::QueryTable<Q>::try_get::h02162e58e862b34e
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:494:9
  26:     0x56031631ca9d - salsa::QueryTable<Q>::get::hce4ec1bd18bbcce4
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:490:9
  27:     0x5603161d7be8 - <DB as sierra_generator::db::SierraGenGroup>::priv_free_function_sierra_data::__shim::h5dcf5fb671026d42
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:17:1
  28:     0x5603161ae00c - <DB as sierra_generator::db::SierraGenGroup>::priv_free_function_sierra_data::h9e43f56a777470dd
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:17:1
  29:     0x560316210e66 - sierra_generator::function_generator::free_function_sierra_diagnostics::hca8725a3375acae6
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/function_generator.rs:55:5
  30:     0x5603161d8107 - <sierra_generator::db::FreeFunctionSierraDiagnosticsQuery as salsa::plumbing::QueryFunction>::execute::h7fdc4251641c77f0
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:66:21
  31:     0x5603162a0194 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}::h1f8e389682b06d1d
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:218:13
  32:     0x5603163a6d3d - salsa::runtime::Runtime::execute_query_implementation::hed52ac40314a984b
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/runtime.rs:330:21
  33:     0x56031628f284 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::h4b669f88ed88cc74
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:215:26
  34:     0x5603162b4cae - salsa::derived::slot::Slot<Q,MP>::read::h3c078c58994ce3d5
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:148:9
  35:     0x56031620d416 - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::ha62f559d745d2030
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived.rs:170:13
  36:     0x56031631de50 - salsa::QueryTable<Q>::try_get::hf37c28b8634befb1
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:494:9
  37:     0x56031631c82d - salsa::QueryTable<Q>::get::h9192b951c414353d
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:490:9
  38:     0x5603161d7c38 - <DB as sierra_generator::db::SierraGenGroup>::free_function_sierra_diagnostics::__shim::h3e405fbdf25d093d
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:17:1
  39:     0x5603161ae09c - <DB as sierra_generator::db::SierraGenGroup>::free_function_sierra_diagnostics::h5ef51ac8d989fde2
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:17:1
  40:     0x56031622cb30 - sierra_generator::program_generator::module_sierra_diagnostics::hf9863b321974fdd3
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/program_generator.rs:33:28
  41:     0x5603161d818b - <sierra_generator::db::ModuleSierraDiagnosticsQuery as salsa::plumbing::QueryFunction>::execute::h153e91909670ee61
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:79:21
  42:     0x5603162a001c - salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}::h118641dd7401ca59
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:218:13
  43:     0x5603163a3dbd - salsa::runtime::Runtime::execute_query_implementation::h102ccec7e02cef40
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/runtime.rs:330:21
  44:     0x56031628b5f4 - salsa::derived::slot::Slot<Q,MP>::read_upgrade::h0b9b85c36c7e708d
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:215:26
  45:     0x5603162b51ce - salsa::derived::slot::Slot<Q,MP>::read::h407ed6dbe63327be
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived/slot.rs:148:9
  46:     0x56031620c706 - <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::h8c715258687fce62
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/derived.rs:170:13
  47:     0x56031631dc04 - salsa::QueryTable<Q>::try_get::h9d480919a2d9445b
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:494:9
  48:     0x56031631c603 - salsa::QueryTable<Q>::get::h1f3c4b77b56503e0
                               at /home/jmcph4/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:490:9
  49:     0x5603161d7ce4 - <DB as sierra_generator::db::SierraGenGroup>::module_sierra_diagnostics::__shim::h3ef25b97d78e2cdf
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:17:1
  50:     0x5603161adf42 - <DB as sierra_generator::db::SierraGenGroup>::module_sierra_diagnostics::h1706dfefce595862
                               at /home/jmcph4/dev/tmp/cairo/crates/sierra_generator/src/db.rs:17:1
  51:     0x5603161aa88b - compiler::diagnostics::check_diagnostics::hc74fb0900de38cf3
                               at /home/jmcph4/dev/tmp/cairo/crates/compiler/src/diagnostics.rs:60:24
  52:     0x5603161a8ec6 - compiler::compile_prepared_db::ha89fb24f3e57441d
                               at /home/jmcph4/dev/tmp/cairo/crates/compiler/src/lib.rs:59:8
  53:     0x5603161a8d07 - compiler::compile_cairo_project_at_path::h1aa28e8a77278bce
                               at /home/jmcph4/dev/tmp/cairo/crates/compiler/src/lib.rs:40:5
  54:     0x5603161a12db - cairo_compile::main::haedc1ec288c31474
                               at /home/jmcph4/dev/tmp/cairo/crates/compiler/src/cli.rs:29:26
  55:     0x5603161a7d9b - core::ops::function::FnOnce::call_once::h15414a5ab5a4753a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  56:     0x56031619ac0e - std::sys_common::backtrace::__rust_begin_short_backtrace::hc44b5c73dd4080c9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  57:     0x5603161a5651 - std::rt::lang_start::{{closure}}::h9adda850af949275
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
  58:     0x5603173fb52f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb69be6e0857c6cfb
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
  59:     0x5603173fb52f - std::panicking::try::do_call::h396dfc441ee9c786
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  60:     0x5603173fb52f - std::panicking::try::h6cdda972d28b3a4f
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  61:     0x5603173fb52f - std::panic::catch_unwind::h376039ec264e8ef9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  62:     0x5603173fb52f - std::rt::lang_start_internal::{{closure}}::hc94720ca3d4cb727
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
  63:     0x5603173fb52f - std::panicking::try::do_call::h2422fb95933fa2d5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  64:     0x5603173fb52f - std::panicking::try::h488286b5ec8333ff
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  65:     0x5603173fb52f - std::panic::catch_unwind::h81636549836d2a25
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  66:     0x5603173fb52f - std::rt::lang_start_internal::h6ba1bb743c1e9df9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  67:     0x5603161a562a - std::rt::lang_start::hcdb1452c5a420608
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:165:17
  68:     0x5603161a2981 - main
  69:     0x7fbf0f946d0a - __libc_start_main
                               at ./csu/../csu/libc-start.c:308:16
  70:     0x5603161983ba - _start
  71:                0x0 - <unknown>
```

**Expected behavior:**

For the compiler to not panic.

**Steps to reproduce:**

See above.

**Related code:**

The site of the direct panic is:

https://github.com/starkware-libs/cairo/blob/03553bd52053dec7fbe49da9cd6c4679843c030a/crates/sierra_generator/src/store_variables/mod.rs#L328-L331

**Other information:**

Notably, this version of the code does **not** induce a panic in the compiler:

```diff
3c3
< func array_sum(arr: felt*, size: felt) -> felt {
---
> func array_sum(arr: felt*, size) -> felt {
```

```
$ cargo run safe_array_sum.cairo
error: Missing token TerminalComma.
 --> safe_array_sum.cairo:3:25
func array_sum(arr: felt*, size) -> felt {
                        ^

error: Skipped tokens. Expected: parameter.
 --> safe_array_sum.cairo:3:25
func array_sum(arr: felt*, size) -> felt {
                        ^

error: Skipped tokens. Expected: parameter.
 --> safe_array_sum.cairo:3:26
func array_sum(arr: felt*, size) -> felt {
                         ^

error: Missing tokens. Expected a type clause.
 --> safe_array_sum.cairo:3:32
func array_sum(arr: felt*, size) -> felt {
                               ^

error: Missing token TerminalSemicolon.
 --> safe_array_sum.cairo:10:15
    return arr[0] + sum_of_rest;
              ^

error: Skipped tokens. Expected: statement.
 --> safe_array_sum.cairo:10:15
    return arr[0] + sum_of_rest;
              ^

error: Skipped tokens. Expected: statement.
 --> safe_array_sum.cairo:10:17
    return arr[0] + sum_of_rest;
                ^

error: Skipped tokens. Expected: statement.
 --> safe_array_sum.cairo:10:19
    return arr[0] + sum_of_rest;
                  ^

error: Unknown type.
 --> safe_array_sum.cairo:3:32
func array_sum(arr: felt*, size) -> felt {
                               ^

error: Binary operator '==' is not supported for types '<missing>' and 'core::felt'.
 --> safe_array_sum.cairo:4:14
    if (size == 0) {
             ^^

error: Cannot assign to an immutable variable.
 --> safe_array_sum.cairo:9:33
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                ^*********^

error: Binary operator '-' is not supported for types '<missing>' and 'core::felt'.
 --> safe_array_sum.cairo:9:56
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                                       ^

error: Cannot assign to an immutable variable.
 --> safe_array_sum.cairo:9:46
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                             ^***********^

error: Unexpected argument type. Expected: "core::felt", found: "()".
 --> safe_array_sum.cairo:9:33
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                ^*********^

error: Unexpected argument type. Expected: "<missing>", found: "()".
 --> safe_array_sum.cairo:9:46
    let sum_of_rest = array_sum(arr=arr + 1, size=size - 1);
                                             ^***********^

error: Unexpected return type. Expected: "core::felt", found: "()".
 --> safe_array_sum.cairo:3:42
func array_sum(arr: felt*, size) -> felt {
                                         ^

Error: Compilation failed.
```

**Comment by spapinistarkware** [comment]
First of all, you are using wrong syntax :) We dont have named paramters, not do we have pointer.
This seems to be occursing because of the return at the end of the function. I have a PR to fix this. For now, just use a tail expression.

**Comment by jmcph4** [comment]
> First of all, you are using wrong syntax :) We dont have named paramters, not do we have pointer.

I just copy-pasted from [the tutorial](https://www.cairo-lang.org/docs/hello_cairo/intro.html#your-first-function) though?

**Comment by spapinistarkware** [comment]
You are confusing Cairo 1.0 with Cairo 0
