### ISSUE TITLE
bug: Automatic dict destructor causes compilation panic

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#2576]
# Bug Report

**Cairo version:**
fd24722ded93f326b87300164ac789cc5b7884e6

**Current behavior:**
`thread 'main' panicked at 'itertools: .zip_eq() reached end of one iterator before the other'`

While I know it is a very recent feature, I think that #2562 made dict destructors possible - apologizes if this is still not entirely implemented.

**Expected behavior:**
The dict is automatically destructed when not used.

**Steps to reproduce:**
Run the following code

**Related code:**
```rust
use dict::Felt252DictTrait;
fn main() {
    let d = Felt252DictTrait::<felt252>::new();
}
```

**Other information:**
Manually calling `d.destruct()` after importing `traits::Destruct` works.

**Comment by spapinistarkware** [comment]
Shoudl be fixed now

**Comment by enitrat** [comment]
Re-opening as the error message is now:

```
thread 'main' panicked at 'Unexpected variable.', crates/cairo-lang-sierra-generator/src/lifetime.rs:113:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/511364e7874dba9649a264100407e4bffe7b5425/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/511364e7874dba9649a264100407e4bffe7b5425/library/core/src/panicking.rs:64:14
   2: cairo_lang_sierra_generator::lifetime::find_variable_lifetime
   3: cairo_lang_sierra_generator::function_generator::priv_function_with_body_sierra_data
   4: salsa::runtime::Runtime::execute_query_implementation
   5: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   6: salsa::derived::slot::Slot<Q,MP>::read
   7: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   8: <DB as cairo_lang_sierra_generator::db::SierraGenGroup>::priv_function_with_body_sierra_data::__shim
   9: salsa::runtime::Runtime::execute_query_implementation
  10: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  11: salsa::derived::slot::Slot<Q,MP>::read
  12: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  13: <DB as cairo_lang_sierra_generator::db::SierraGenGroup>::function_with_body_sierra::__shim
  14: <cairo_lang_sierra_generator::db::GetSierraProgramForFunctionsQuery as salsa::plumbing::QueryFunction>::execute
  15: salsa::runtime::Runtime::execute_query_implementation
  16: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  17: salsa::derived::slot::Slot<Q,MP>::read
  18: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  19: salsa::QueryTable<Q>::get
  20: <DB as cairo_lang_sierra_generator::db::SierraGenGroup>::get_sierra_program_for_functions::__shim
  21: <cairo_lang_sierra_generator::db::GetSierraProgramQuery as salsa::plumbing::QueryFunction>::execute
  22: salsa::runtime::Runtime::execute_query_implementation
  23: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  24: salsa::derived::slot::Slot<Q,MP>::read
  25: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  26: salsa::QueryTable<Q>::get
  27: <DB as cairo_lang_sierra_generator::db::SierraGenGroup>::get_sierra_program::__shim
  28: cairo_run::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
