### ISSUE TITLE
bug: starknet-compile 'entered unreachable code' in `cairo_lang_starknet::abi::AbiBuilder::add_event`

### ISSUE THREAD

**Issue by moodysalem** [starkware-libs/cairo#3568]
# Bug Report

**Cairo version:**
main @ 4055399e5ce619845ffc140535eb03e1d1aaf6f2

**Current behavior:**

`starknet-compile --allowed-libfuncs-list-name all . -c ekubo::core::Core out/core.json`

panics with this backtrace at this line
https://github.com/starkware-libs/cairo/blob/4055399e5ce619845ffc140535eb03e1d1aaf6f2/crates/cairo-lang-starknet/src/abi.rs#L470

```
thread 'main' panicked at 'internal error: entered unreachable code', crates/cairo-lang-starknet/src/abi.rs:470:78
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: cairo_lang_starknet::abi::AbiBuilder::add_event
   4: cairo_lang_starknet::abi::AbiBuilder::add_event_field
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   7: core::iter::adapters::try_process
   8: cairo_lang_starknet::abi::AbiBuilder::add_event
   9: cairo_lang_starknet::abi::AbiBuilder::submodule_as_contract_abi
  10: cairo_lang_starknet::contract_class::compile_contract_with_prepared_and_checked_db
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  12: core::iter::adapters::try_process
  13: cairo_lang_starknet::contract_class::compile_contract_in_prepared_db
  14: cairo_lang_starknet::contract_class::compile_path
  15: cairo_lang_starknet::contract_class::starknet_compile
  16: starknet_compile::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Expected behavior:**

Compiles and produces output JSON artifact

**Steps to reproduce:**

Several of my contracts are failing to compile due to this error

**Comment by ilyalesokhin-starkware** [comment]
Can you post the source code that triggers the error?

**Comment by tensojka** [comment]
I also ran into this issue, tried to make a minimal example that triggers this error: https://github.com/CarmineOptions/governance/pull/10

Note that while moody and me are working on the same thing (governance), the code is mostly very different.
