### ISSUE TITLE
bug: Compiler panics from `compute_expr_function_call_semantic`

### ISSUE THREAD

**Issue by mkaput** [starkware-libs/cairo#5485]
# Bug Report

**Cairo version:**

2.6.3

**Steps to reproduce:**

```rust
#[starknet::interface]
trait ISimpleStorage<TContractState> {
    fn set(ref self: TContractState, x: u128);
    fn get(self: @TContractState) -> u128;
    fn is_valid_signature(ref self: TContractState, pk: felt252);
}

#[starknet::contract]
mod SimpleStorage {
    use starknet::{get_caller_address, contract_address_const};
    use starknet::secp256_trait::is_valid_signature;

    #[storage]
    struct Storage {
        stored_data: u128
    }

    #[abi(embed_v0)]
    impl SimpleStorage of super::ISimpleStorage<ContractState> {
        fn set(ref self: ContractState, x: u128) {
            let caller_felt: felt252 = get_caller_address().into();
            println!("Caller : {}", caller_felt);
            assert!(get_caller_address() != contract_address_const::<0>(), "Caller is 0");
            self.stored_data.write(x);
        }

        fn get(self: @ContractState) -> u128 {
            self.stored_data.read()
        }
        fn is_valid_signature(ref self: ContractState, pk: felt252) {
            is_valid_signature()
        }
    }
}
#[cfg(test)]
mod test {
    use result::ResultTrait;
    use core::traits::TryInto;
    use starknet::testing::set_caller_address;
    use starknet::contract_address_const;
    use super::{ISimpleStorageDispatcher, ISimpleStorageDispatcherTrait};

    #[test]
    fn test_fail() {
        let (address, _) = starknet::deploy_syscall(
            super::SimpleStorage::TEST_CLASS_HASH.try_into().unwrap(), 0, array![].span(), true
        )
            .unwrap();
        let hello_dispatcher = ISimpleStorageDispatcher { contract_address: address };
        let one_address = contract_address_const::<1>();
        set_caller_address(one_address);
        hello_dispatcher.set(1);
    }
}
```

```shell
RUST_BACKTRACE=1 scarb build
```

```
   Compiling hello_scarb v0.1.0 (/Users/mk/Developer/hello_scarb/Scarb.toml)
thread 'main' panicked at /Users/runner/.cargo/git/checkouts/cairo-f086c7e6d4098a68/de1d5b1/crates/cairo-lang-semantic/src/expr/compute.rs:1019:55:
More parameters than arguments
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: cairo_lang_semantic::expr::compute::compute_expr_function_call_semantic
   4: cairo_lang_semantic::expr::compute::maybe_compute_expr_semantic
   5: cairo_lang_semantic::expr::compute::compute_expr_semantic
   6: cairo_lang_semantic::expr::compute::ComputationContext::run_in_subscope
   7: cairo_lang_semantic::expr::compute::compute_root_expr
   8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   9: <DB as cairo_lang_semantic::db::SemanticGroup>::priv_impl_function_body_data::__shim
  10: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  11: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_function_body_diagnostics::__shim
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_semantic_definition_diagnostics::__shim
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: <DB as cairo_lang_semantic::db::SemanticGroup>::module_semantic_diagnostics::__shim
  16: cairo_lang_compiler::diagnostics::DiagnosticsReporter::ensure
  17: <scarb::compiler::compilers::lib::LibCompiler as scarb::compiler::Compiler>::compile
  18: scarb::ops::compile::compile
  19: scarb::commands::run
  20: scarb::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Related code:**

https://github.com/starkware-libs/cairo/blob/d8d0e04b2a5c86a06207cc1a6dda8e4626700164/crates/cairo-lang-semantic/src/expr/compute.rs#L1017

reported by @LucasLvy

**Comment by orizi** [comment]
Can you actually recreate this on main? this just seems to bring up a proper diagnostic for me.

**Comment by mkaput** [comment]
```
➜  hello_scarb scarb --version
scarb 2.6.3+nightly-2024-04-27 (a3cdd7ca1 2024-04-27)
cairo: 2.6.3 (233c0fdab)
sierra: 1.5.0

➜  hello_scarb RUST_BACKTRACE=1 scarb build
   Compiling hello_scarb v0.1.0 (/Users/mk/Developer/hello_scarb/Scarb.toml)
thread 'main' panicked at /Users/runner/.cargo/git/checkouts/cairo-f086c7e6d4098a68/233c0fd/crates/cairo-lang-semantic/src/expr/compute.rs:1015:55:
More parameters than arguments
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: cairo_lang_semantic::expr::compute::compute_expr_function_call_semantic
   4: cairo_lang_semantic::expr::compute::maybe_compute_expr_semantic
   5: cairo_lang_semantic::expr::compute::compute_expr_semantic
   6: cairo_lang_semantic::expr::compute::ComputationContext::run_in_subscope
   7: cairo_lang_semantic::expr::compute::compute_root_expr
   8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   9: <DB as cairo_lang_semantic::db::SemanticGroup>::priv_impl_function_body_data::__shim
  10: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  11: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_function_body_diagnostics::__shim
  12: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  13: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_semantic_definition_diagnostics::__shim
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: <DB as cairo_lang_semantic::db::SemanticGroup>::module_semantic_diagnostics::__shim
  16: cairo_lang_compiler::diagnostics::DiagnosticsReporter::ensure
  17: <scarb::compiler::compilers::lib::LibCompiler as scarb::compiler::Compiler>::compile
  18: scarb::ops::compile::compile
  19: scarb::commands::run
  20: scarb::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'll check this on latest-latest `main` in an hour.

**Comment by LucasLvy** [comment]
```
 RUST_BACKTRACE=1 ../cairo/target/release/starknet-compile src/lib.cairo --single-file                                                                       101 ✘    10:03:14
thread 'main' panicked at crates/cairo-lang-semantic/src/expr/compute.rs:1019:55:
More parameters than arguments
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1980:5
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   6: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   7: cairo_lang_semantic::expr::compute::compute_expr_function_call_semantic
   8: cairo_lang_semantic::expr::compute::maybe_compute_expr_semantic
   9: cairo_lang_semantic::expr::compute::compute_expr_semantic
  10: cairo_lang_semantic::expr::compute::ComputationContext::run_in_subscope
  11: cairo_lang_semantic::expr::compute::compute_root_expr
  12: cairo_lang_semantic::items::imp::priv_impl_function_body_data
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as cairo_lang_semantic::db::SemanticGroup>::priv_impl_function_body_data::__shim
  18: cairo_lang_semantic::items::imp::impl_function_body_diagnostics
  19: salsa::runtime::Runtime::execute_query_implementation
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_function_body_diagnostics::__shim
  24: cairo_lang_semantic::items::imp::impl_semantic_definition_diagnostics
  25: salsa::runtime::Runtime::execute_query_implementation
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::read
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  29: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_semantic_definition_diagnostics::__shim
  30: <cairo_lang_semantic::db::ModuleSemanticDiagnosticsQuery as salsa::plumbing::QueryFunction>::execute
  31: salsa::runtime::Runtime::execute_query_implementation
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  35: <DB as cairo_lang_semantic::db::SemanticGroup>::module_semantic_diagnostics::__shim
  36: cairo_lang_compiler::diagnostics::DiagnosticsReporter::check
  37: cairo_lang_starknet::compile::compile_contract_in_prepared_db
  38: cairo_lang_starknet::compile::compile_path
  39: cairo_lang_starknet::compile::starknet_compile
  40: starknet_compile::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by LucasLvy** [comment]
```
git show  --oneline -s 
5c95ac153 (HEAD -> main, upstream/main) Added phantom types checks. (#5482)
```

```
 RUST_BACKTRACE=1 ../cairo/target/release/starknet-compile src/lib.cairo --single-file                                                                           ✔    10:05:24
thread 'main' panicked at crates/cairo-lang-semantic/src/expr/compute.rs:1015:55:
More parameters than arguments
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1980:5
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   6: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   7: cairo_lang_semantic::expr::compute::compute_expr_function_call_semantic
   8: cairo_lang_semantic::expr::compute::maybe_compute_expr_semantic
   9: cairo_lang_semantic::expr::compute::compute_expr_semantic
  10: cairo_lang_semantic::expr::compute::ComputationContext::run_in_subscope
  11: cairo_lang_semantic::expr::compute::compute_root_expr
  12: cairo_lang_semantic::items::imp::priv_impl_function_body_data
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  17: <DB as cairo_lang_semantic::db::SemanticGroup>::priv_impl_function_body_data::__shim
  18: cairo_lang_semantic::items::imp::impl_function_body_diagnostics
  19: salsa::runtime::Runtime::execute_query_implementation
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_function_body_diagnostics::__shim
  24: cairo_lang_semantic::items::imp::impl_semantic_definition_diagnostics
  25: salsa::runtime::Runtime::execute_query_implementation
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::read
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  29: <DB as cairo_lang_semantic::db::SemanticGroup>::impl_semantic_definition_diagnostics::__shim
  30: <cairo_lang_semantic::db::ModuleSemanticDiagnosticsQuery as salsa::plumbing::QueryFunction>::execute
  31: salsa::runtime::Runtime::execute_query_implementation
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  35: <DB as cairo_lang_semantic::db::SemanticGroup>::module_semantic_diagnostics::__shim
  36: cairo_lang_compiler::diagnostics::DiagnosticsReporter::check
  37: cairo_lang_starknet::compile::compile_contract_in_prepared_db
  38: cairo_lang_starknet::compile::compile_path
  39: cairo_lang_starknet::compile::starknet_compile
  40: starknet_compile::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
