### ISSUE TITLE
bug: cairo-test panic in cairo-lang-lowering-2.7.0/src/lower/context.rs:264:55

### ISSUE THREAD

**Issue by maciektr** [starkware-libs/cairo#6207]
Originally reported in https://github.com/software-mansion/scarb/issues/1507
Tested with cairo-test 2.7.0 and 2.7.1 - with same effect. 
Original report below:

### Problem

I got this weird error when running `scarb test` on a simple module.

```shell
scarb test
     Running cairo-test kron
   Compiling test(kron_unittest) kron v0.1.0 (/Users/m/projects/tmp/kron/Scarb.toml)
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-lowering-2.7.0/src/lower/context.rs:264:55:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: `scarb metadata` exited with error
```

### Steps

1. Create a new scarb project with `scarb init`, select Cairo Test as the test runner.
2. Replace the contents of `lib.cairo` with the following:

```cairo
#[derive(Drop, Copy, PartialEq)]
pub enum KronError {
    UnequalLength,
}

pub fn kron<T, +Mul<T>, +Copy<T>, +Drop<T>,>(
    mut xs: Span<T>, mut ys: Span<T>
) -> Result<Array<T>, KronError> {
    if xs.len() != ys.len() {
        return Result::Err(KronError::UnequalLength);
    }
    let mut array = array![];
    for x_value in xs {
        let ys_clone = ys;
        for y_value in ys {
            array.append(*x_value * *y_value);
        }
    };
    Result::Ok(array)
}

#[test]
#[available_gas(2000000)]
fn kron_product_test() {
    let xs = array![1_u64, 10, 100];
    let ys = array![5, 6, 7];
    let zs = kron(xs.span(), ys.span()).unwrap();
    assert_eq!(*zs[0], 5);
    assert_eq!(*zs[1], 6);
    assert_eq!(*zs[2], 7);
    assert_eq!(*zs[3], 50);
    assert_eq!(*zs[4], 60);
    assert_eq!(*zs[5], 70);
    assert_eq!(*zs[6], 500);
    assert_eq!(*zs[7], 600);
    assert_eq!(*zs[8], 700);
}

#[test]
#[available_gas(2000000)]
fn kron_product_test_check_len() {
    let xs = array![1_u64];
    let ys = array![];
    assert!(kron(xs.span(), ys.span()) == Result::Err(KronError::UnequalLength));
}
```

3. Run `scarb test`, you should see the following output:

```shell
scarb test
     Running cairo-test kron
   Compiling test(kron_unittest) kron v0.1.0 (/Users/m/projects/tmp/kron/Scarb.toml)
warn[E0001]: Unused variable. Consider ignoring by prefixing with `_`.
 --> /Users/m/projects/tmp/kron/src/lib.cairo:14:13
        let ys_clone = ys;
            ^******^

    Finished release target(s) in 2 seconds
testing kron ...
running 2 tests
test kron::kron_product_test ... ok (gas usage est.: 206110)
test kron::kron_product_test_check_len ... ok (gas usage est.: 66140)
test result: ok. 2 passed; 0 failed; 0 ignored; 0 filtered out;
```

4. Notice the warning on line 14. Now edit the code in `lib.cairo`, commenting out the whole line 14. Run `scarb test` again. That's when the issue happens:

```shell
scarb test
     Running cairo-test kron
   Compiling test(kron_unittest) kron v0.1.0 (/Users/m/projects/tmp/kron/Scarb.toml)
thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-lowering-2.7.0/src/lower/context.rs:264:55:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: `scarb metadata` exited with error
```

### Version

```text
scarb --version
scarb 2.7.0 (e9a2b8716 2024-08-01)
cairo: 2.7.0 (https://crates.io/crates/cairo-lang-compiler/2.7.0)
sierra: 1.6.0
```

**Comment by orizi** [comment]
doesn't happen on main with `cairo-test`.

**Comment by orizi** [comment]
@maciektr - please replicate at cairo scope or close.

**Comment by maciektr** [comment]
Yep, no longer happening on main, still present in 2.7.1 though.

**Comment by orizi** [comment]
Didn't happen for me on 2.7.0 and 2.7.1 as well.

**Comment by maciektr** [comment]
@orizi 
Please take a look at this repro, it works for current Cairo main but fails for 2.7.1 

https://github.com/maciektr/cairo-test-run/blob/main/src/lib.cairo
https://github.com/maciektr/cairo-test-run/actions/runs/10480423181/job/29028037875

**Comment by orizi** [comment]
Ok - this was indeed a for `variable usage` issue - and was specifically solved on main.
