### ISSUE TITLE
bug: compiler panics when defining default trait impl

### ISSUE THREAD

**Issue by cairolover** [starkware-libs/cairo#6946]
# Bug Report

**Cairo version:**
2.9.2

**Current behavior:**
While working on iterators I wanted to implement `advance_by` which is basically a loop of `next`. As such the implementation is the same for all types, and I was writing the default trait impl as:

```rust
/// An iterator over a collection of values.
pub trait Iterator<T> {
    /// The type of the elements being iterated over.
    type Item;

    /// Advance the iterator and return the next value.
    fn next(ref self: T) -> Option<Self::Item>;

    fn advance_by(ref self: T, n: usize) -> Result<(), NonZero<usize>> {
        let mut res = Result::Ok(());
        for i in 0..n {
            if Self::next(ref self).is_none() {
                res = Result::Err((n - i).try_into().unwrap());
                break;
            }
        };
        res
    }
}
```

However, this breaks compilation with:

```
thread 'scarb compile tmp-lk338q382tp00' panicked at /Users/runner/.cargo/git/checkouts/cairo-f086c7e6d4098a68/809dfef/crates/cairo-lang-semantic/src/substitution.rs:493:21:
assertion `left == right` failed
  left: TraitId(0)
 right: TraitId(7)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at scarb/src/ops/compile.rs:197:14:
Compiler thread has panicked.: Any { .. }
```

**Expected behavior:**
This should compile successfully or fail compilation but without a panic

**Steps to reproduce:**
Create an isolated cairo file with:

```rust
/// An iterator over a collection of values.
pub trait Iterator2<T> {
    /// The type of the elements being iterated over.
    type Item;

    /// Advance the iterator and return the next value.
    fn next(ref self: T) -> Option<Self::Item>;
    
    fn advance_by(ref self: T, n: usize) -> Result<(), NonZero<usize>> {
        let mut res = Result::Ok(());
        for i in 0..n {
            if Self::next(ref self).is_none() {
                res = Result::Err((n - i).try_into().unwrap());
                break;
            }
        };
        res
    }
}
```

without `advance_by` - runs fine. with, panics

**Comment by julio4** [comment]
I'm also encountering a similar issue. I'll describe it here as I think it may have the same root cause.
Using closure in default trait impl fails with "Function not found"

#### Cairo version:
2.9.2

#### To reproduce:

```cairo
#[generate_trait]
impl TraitImpl of Trait {
    fn call<T, F, +Drop<F>, impl func: core::ops::FnOnce<F, ()>[Output: T], +Drop<T>>(f: F) {
        f();
        // Ok
    }
}

pub trait DefaultTraitImpl {
    fn call<T, F, +Drop<F>, impl func: core::ops::FnOnce<F, ()>[Output: T], +Drop<T>>(f: F) {
        f();
     // ˆ Function not found.
    }
}
```
